apiVersion: v1
kind: ConfigMap
metadata:
  name: incidentboard-config
  labels: {{- include "ib.labels" . | nindent 4 }}
data:
  ENVIRONMENT: {{ .Values.config.environment | quote }}
  BANNER: {{ .Values.config.banner | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: incidentboard-db
  labels: {{- include "ib.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  DATABASE_URL: "postgresql+psycopg://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@incidentboard-postgres:5432/{{ .Values.postgres.database }}"
